# Network
bind 127.0.0.1
port 6379

# Persistence
dbfilename dump.rdb
appendfilename appendonly.aof
appendincrfilename appendonly.aof.incr

# Seconds. Set to 0 to disable the background task.
appendfsync-seconds 2
save-seconds 60

# Seconds. Set to 0 to disable idle connection timeout.
idle-timeout-seconds 300
